version: "3.9"

services:
  backend:
    build: ./backend
    container_name: chatclass_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - chatnet

  frontend:
    build: ./frontend
    container_name: chatclass_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
